name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: versioning
        if: "${{ !contains(github.event.pull_request.labels.*.name, 'release-candidate') }}"
        uses: ./.github/actions/version-update
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}


      - name: setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      

      - name: install dependencies
        run: dotnet restore

      - name: build
        run: dotnet build