name: Create release

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write
  repository-projects: write

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 200

      - name: Create release
        working-directory: .github/actions/versioning
        run: |
          git fetch --tags
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          npm run version:create-release
        env:
          GH_TOKEN: ${{ secrets.MY_PAT_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build
