name: Release Candidate

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: write
  issues: write
  pull-requests: write
  repository-projects: read

jobs:
  versioning:
    name: Create Release Candidate
    if: "${{ !startsWith(github.event.head_commit.message, 'chore: release v') }}"
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 200

      - name: Create Release Candidate
        id: create-release-candidate
        working-directory: .github/actions/versioning
        shell: bash
        run: |
          git fetch --tags
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          pnpm run version:release-candidate
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}