name: Release Candidate

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write
  repository-projects: write

jobs:
  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'chore: release v')}}"

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 200
      
      - name: Release candidate
        working-directory: .github/actions/versioning
        run: |
          git fetch --tags
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          npm run version:release-candidate
        env:
          GH_TOKEN: ${{ secrets.MY_PAT_TOKEN }}

          
